server:
  port: 8080

logging:
  level:
    root: DEBUG

# ToDo - these needs to be taken as input params ot the application!
bidders: "http://localhost:8081, http://localhost:8082, http://localhost:8083"